[tool.poetry]
name = "lambdas"
version = "0.1.0"
description = ""
authors = ["Anthony Viera <anthonyviera4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.103.2"
mangum = "^0.17.0"
boto3 = "^1.34.55"
aws-lambda-powertools = "^2.34.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
