name: CI/CD Pipeline

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  # ecr-build-push-us-east-1:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set GIT variables
  #       run: |
  #         echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
  #         echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_ENV

  #     - name: Configure AWS credentials for us-east-1
  #       uses: aws-actions/configure-aws-credentials@v3
  #       with:
  #         role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
  #         aws-region: us-east-1

  #     - name: Login to ECR
  #       id: login-ecr-east
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Build, tag, and push docker image to Amazon ECR
  #       env:
  #         REGISTRY: ${{ steps.login-ecr-east.outputs.registry }}
  #         REPOSITORY: paradise-cakes-api-lambdas-us-east-1
  #       run: |
  #         docker build -t $REGISTRY/$REPOSITORY:${BRANCH_NAME}-${SHORT_SHA} ${GITHUB_WORKSPACE}/lambdas
  #         docker push $REGISTRY/$REPOSITORY:${BRANCH_NAME}-${SHORT_SHA} 
        
  deploy:
    # needs: ecr-build-push-us-east-1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set GIT variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_ENV
      
      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.2.7

      - name: Terraform Init
        id: tf-init-us-east-1
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform init \
            --backend-config="bucket=paradise-cakes-api-tfstate" \
            --backend-config="key=paradise-cakes-api.tfstate"

      - name: Terraform Plan
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform plan --out tfplan.out
      
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform apply --auto-approve tfplan.out
          


