name: CI/CD Pipeline

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Run unit tests
      #   run: |
      #     # Add commands to run your unit tests here

  ecr-build-push-us-east-1:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set GIT variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_ENV

      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::132899756990:role/paradise-cakes-api-terraform-deployer
          role-session-name: paradise-cakes-api-terraform-deployer
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and push Lambda Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.GITHUB_WORKSPACE }}
          file: ./lambdas/Dockerfile
          push: true
          tags: paradise-cakes-api-lambdas-us-east-1:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}
    
  deploy:
    needs: ecr-build-push-us-east-1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set GIT variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_ENV
      
      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v2.0.0
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.2.7

      - name: Terraform Init
        id: tf-init-us-east-1
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform init \
            --backend-config="bucket=paradise-cakes-state" \
            --backend-config="key=remote-state.terraform.tfstate"

      - name: Terraform Plan
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
      
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/head/main' }}
        run: |
          cd ${GITHUB_WORKSPACE}/terraform
          terraform apply --auto-approve tfplan.out
          


